# Generated by Django 4.2.6 on 2023-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
