# Generated by Django 4.2.6 on 2023-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
