# Generated by Django 4.2.6 on 2023-11-08 08:04

from django.db import migrations, models
import django.db.models.deletion

def delete_data(apps, schema_editor):
    # Access your models via the apps parameter
    Message = apps.get_model('chats', 'Message')
    Chat = apps.get_model('chats', 'Chat')

    # Delete all messages and chats
    Message.objects.all().delete()
    Chat.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
        migrations.RunPython(delete_data),
    ]
